### ISSUE TITLE
Fighting to get Leviton Switches working

### ISSUE THREAD

**Issue by frogbite** [hassio-addons/addon-zwavejs2mqtt#119]
# Problem/Motivation

I recently went from OZW to Zwave JS with the official add-on.  Had the devices there but was having intermittent issues with my automations with my Leviton switches work some times but not others.  So I deinstalled the official add one and installed the mqtt2zwave add-on.  

After doing this, my Leviton switches, one is a "Leviton - DZ15S - Scene Capable Push On/Off" the other is a dimmer.  Both went to a dead status.  So after many exclusions and inclusions where the switches would be added in but would always show as unknown.  Also, attempted healing the network many times.  In the end I did a factory reset on my AEON z-stick and added my motion sensor back in and then tried to add the DZ15S back in which resulted in the same result.   Many reboots were done as well.

[nodes.json_before_readding.txt](https://github.com/hassio-addons/addon-zwavejs2mqtt/files/6289054/nodes.json_before_readding.txt)

It won't let me upload the new, it says it is empty. 

## Expected behavior

I would expect after an inclusion that the devices would be recognized.   Interviews always return with:

## Actual behavior

2021-04-09 20:49:16.684 INFO ZWAVE: Node 4: interview stage COMMANDCLASSES completed
2021-04-09 20:49:16.694 INFO ZWAVE: Node 4: interview stage OVERWRITECONFIG completed
2021-04-09 20:49:16.751 INFO ZWAVE: Node 4: interview stage NEIGHBORS completed
2021-04-09 20:49:16.754 INFO ZWAVE: Node 4: interview stage COMPLETE completed
2021-04-09 20:49:16.780 INFO ZWAVE: Node 4: value added 4-37-0-currentValue => undefined
2021-04-09 20:49:16.784 INFO ZWAVE: Node 4: value added 4-37-0-targetValue => undefined
2021-04-09 20:49:16.787 INFO ZWAVE: Node 4: value added 4-134-0-libraryType => undefined
2021-04-09 20:49:16.790 INFO ZWAVE: Node 4: value added 4-134-0-protocolVersion => undefined
2021-04-09 20:49:16.793 INFO ZWAVE: Node 4: value added 4-134-0-firmwareVersions => undefined
2021-04-09 20:49:16.795 INFO ZWAVE: Node 4: value added 4-114-0-manufacturerId => undefined
2021-04-09 20:49:16.804 INFO ZWAVE: Node 4: value added 4-114-0-productType => undefined
2021-04-09 20:49:16.807 INFO ZWAVE: Node 4: value added 4-114-0-productId => undefined
2021-04-09 20:49:16.809 INFO ZWAVE: Node 4: value added 4-43-0-sceneId => undefined
2021-04-09 20:49:16.813 INFO ZWAVE: Node 4: value added 4-43-0-dimmingDuration => undefined
2021-04-09 20:49:16.819 INFO ZWAVE: Node 4 ready: Unknown manufacturer 0xXXXX - Unknown product 0xXXXX (0xXXXX)
2021-04-09 20:49:16.822 INFO ZWAVE: Controller status: Scan completed
2021-04-09 20:49:16.825 INFO ZWAVE: Network scan complete. Found: 3 nodes
2021-04-09 20:49:16.849 INFO ZWAVE: Node 4: interview COMPLETED, all values are updated
2021-04-09 20:49:22.909 INFO APP: GET /health/zwave 200 6.197 ms - 1875
2021-04-09 20:50:18.515 INFO APP: GET /api/store 200 32.056 ms - 735

I am now seeing:

2021-04-09 20:50:18.515 INFO APP: GET /api/store 200 32.056 ms - 735
Error: Not Found
at /opt/app.js:979:15
at Layer.handle [as handle_request] (/opt/node_modules/express/lib/router/layer.js:95:5)
at trim_prefix (/opt/node_modules/express/lib/router/index.js:317:13)
at /opt/node_modules/express/lib/router/index.js:284:7
at Function.process_params (/opt/node_modules/express/lib/router/index.js:335:12)
at next (/opt/node_modules/express/lib/router/index.js:275:10)
at /opt/node_modules/express-session/index.js:502:7
at readCallback (/opt/node_modules/session-file-store/lib/session-file-helpers.js:193:20)
at /opt/node_modules/graceful-fs/graceful-fs.js:123:16
at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
2021-04-09 20:50:24.258 INFO APP: GET /api/store//data/store/settings.json 404 25.652 ms - 136
2021-04-09 20:51:22.940 INFO APP: GET /health/zwave 200 5.265 ms - 1875
Error: Not Found
at /opt/app.js:979:15
at Layer.handle [as handle_request] (/opt/node_modules/express/lib/router/layer.js:95:5)
at trim_prefix (/opt/node_modules/express/lib/router/index.js:317:13)
at /opt/node_modules/express/lib/router/index.js:284:7
at Function.process_params (/opt/node_modules/express/lib/router/index.js:335:12)
at next (/opt/node_modules/express/lib/router/index.js:275:10)
at /opt/node_modules/express-session/index.js:502:7
at readCallback (/opt/node_modules/session-file-store/lib/session-file-helpers.js:193:20)
at /opt/node_modules/graceful-fs/graceful-fs.js:123:16
at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)

I looked at the file in the "Store" area and it is there but does not look like it is in good shape.  I downloaded it and will include. 

I did not have this error until I did an exclude where the node was node 3.  I excluded and included the node and it is now it is node 4.  

## Steps to reproduce

Not sure, at this point not sure how to get the nodes.js fixed.  I do have a backup from when the Leviton switch was node 3. 

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frogbite** [comment]
![image](https://user-images.githubusercontent.com/38390153/114253929-8f0d3780-997a-11eb-9dff-fcd63b6cbcc4.png)

**Comment by frogbite** [comment]
This is interesting, I bounced my rpi and node 3 showed back, but it was excluded.

![image](https://user-images.githubusercontent.com/38390153/114254115-8a954e80-997b-11eb-8e23-cbf5f5de6b41.png)

Unless you want me to do something else, I will remove the integration and plugin and reinstall.   Just did not want to blow this away in case it may be useful.

**Comment by frenck** [comment]
Hi there, thanks for opening an issue, unfortunately, this is not something I can fix from an add-on perspective.

Add-ons wrap existing applications. The error originates from the application wrapped by this add-on. Please report this issue upstream. Thanks! 👍

**Comment by frogbite** [comment]
Hi frenck, 

First, I think the work with the console is awesome.  A big improvement.  As far as reporting this upstream, you thinking that I should look into filing this under the Z-Wave JS inegration?

**Comment by frogbite** [comment]
Looking at the log, it looks like the add-on is getting a timeout:

2021-04-15T22:40:19.770Z CNTRLR » [Node 004] querying protocol info...
2021-04-15 18:40:19.813 INFO ZWAVE: Success zwave api call refreshInfo { success: true, message: 'Success zwave api call', result: undefined }
2021-04-15T22:40:19.857Z CNTRLR « [Node 004] received response for protocol info:
basic device class: Routing Slave
generic device class: Binary Switch
specific device class: Binary Power Switch
node type: Routing End Node
is always listening: true
is frequent listening: false
can route messages: true
supports security: false
supports beaming: true
maximum data rate: 100000 kbps
protocol version: 3
2021-04-15 18:40:19.861 INFO ZWAVE: Node 4: interview stage PROTOCOLINFO completed
2021-04-15T22:40:19.867Z CNTRLR [Node 004] Interview stage completed: ProtocolInfo
2021-04-15T22:40:19.870Z CNTRLR » [Node 004] querying node info...
2021-04-15T22:40:20.173Z CNTRLR « [Node 004] node info received
supported CCs:
· Z-Wave Plus Info
· Association
· Association Group Information
· Version
· Manufacturer Specific
· Configuration
· Device Reset Locally
· Powerlevel
· Binary Switch
· Basic
· All Switch
· Scene Actuator Configuration
· Scene Activation
· Firmware Update Meta Data
controlled CCs:
· Hail
2021-04-15 18:40:20.181 INFO ZWAVE: Node 4: interview stage NODEINFO completed
2021-04-15T22:40:20.208Z CNTRLR [Node 004] Interview stage completed: NodeInfo
2021-04-15T22:40:20.218Z CNTRLR [Node 004] Interviewing Manufacturer Specific...
2021-04-15T22:40:20.222Z CNTRLR » [Node 004] querying manufacturer information...
2021-04-15T22:40:20.423Z CNTRLR « [Node 004] Received updated node info
2021-04-15T22:40:20.811Z CNTRLR « [Node 004] Received updated node info
2021-04-15 18:40:23.100 INFO ZWAVE: Node 2: value updated: 113-0-Home Security-Motion sensor status 8 => 8
2021-04-15 18:40:23.112 INFO ZWAVE: Node 2: metadata updated: 48-0-Motion
2021-04-15 18:40:23.118 INFO ZWAVE: Node 2: value updated: 48-0-Motion true => true
2021-04-15T22:40:30.506Z CNTRLR [Node 004] Timed out while waiting for a response from the node
2021-04-15T22:40:30.531Z CNTRLR [Node 004] Interviewing Version...
2021-04-15T22:40:30.533Z CNTRLR » [Node 004] querying node versions...
2021-04-15 18:40:38.961 INFO ZWAVE: Node 2: value updated: 113-0-Home Security-Motion sensor status 8 => 8
2021-04-15 18:40:38.975 INFO ZWAVE: Node 2: metadata updated: 48-0-Motion
2021-04-15 18:40:38.979 INFO ZWAVE: Node 2: value updated: 48-0-Motion true => true
2021-04-15T22:40:40.770Z CNTRLR [Node 004] Timed out while waiting for a response from the node
2021-04-15T22:40:40.774Z CNTRLR » [Node 004] querying CC versions...
2021-04-15T22:40:40.776Z CNTRLR » [Node 004] querying the CC version for Binary Switch...
2021-04-15T22:40:51.084Z CNTRLR [Node 004] Timed out while waiting for a response from the node
2021-04-15T22:40:51.089Z CNTRLR [Node 004] CC version query for Binary Switch timed out - assuming the node su
pports version 1...
2021-04-15T22:40:51.091Z CNTRLR [Node 004] skipping query for All Switch (0x27) because max implemented vers
ion is 0
2021-04-15T22:40:51.092Z CNTRLR » [Node 004] querying the CC version for Z-Wave Plus Info...
2021-04-15T22:40:55.398Z CNTRLR [Node 004] did not respond after 1/3 attempts. Scheduling next try in 500 ms.
2021-04-15T22:41:06.095Z CNTRLR [Node 004] Timed out while waiting for a response from the node
2021-04-15T22:41:06.100Z CNTRLR [Node 004] CC version query for Z-Wave Plus Info timed out - assuming the node
supports version 1...
2021-04-15T22:41:06.104Z CNTRLR » [Node 004] querying the CC version for Association...
2021-04-15 18:41:10.386 INFO ZWAVE: Node 2: value updated: 113-0-Home Security-Motion sensor status 8 => 0
2021-04-15 18:41:10.400 INFO ZWAVE: Node 2: metadata updated: 48-0-Motion
2021-04-15 18:41:10.405 INFO ZWAVE: Node 2: value updated: 48-0-Motion true => false
2021-04-15T22:41:16.176Z CNTRLR [Node 004] Timed out while waiting for a response from the node
2021-04-15T22:41:16.179Z CNTRLR [Node 004] CC version query for Association timed out - assuming the node supp
orts version 1...
2021-04-15T22:41:16.180Z CNTRLR » [Node 004] querying the CC version for Association Group Information...
2021-04-15T22:41:26.350Z CNTRLR [Node 004] Timed out while waiting for a response from the node
2021-04-15T22:41:26.355Z CNTRLR [Node 004] CC version query for Association Group Information timed out - assu
ming the node supports version 1...
2021-04-15T22:41:26.357Z CNTRLR » [Node 004] querying the CC version for Version...
2021-04-15T22:41:36.414Z CNTRLR [Node 004] Timed out while waiting for a response from the node
2021-04-15T22:41:36.419Z CNTRLR [Node 004] CC version query for Version timed out - assuming the node supports
version 1...
2021-04-15T22:41:36.420Z CNTRLR » [Node 004] querying the CC version for Manufacturer Specific...
2021-04-15T22:41:46.484Z CNTRLR [Node 004] Timed out while waiting for a response from the node
2021-04-15T22:41:46.488Z CNTRLR [Node 004] CC version query for Manufacturer Specific timed out - assuming the
node supports version 1...
2021-04-15T22:41:46.489Z CNTRLR » [Node 004] querying the CC version for Configuration...
2021-04-15T22:41:56.731Z CNTRLR [Node 004] Timed out while waiting for a response from the node
2021-04-15T22:41:56.736Z CNTRLR [Node 004] CC version query for Configuration timed out - assuming the node su
pports version 1...
2021-04-15T22:41:56.738Z CNTRLR [Node 004] skipping query for Device Reset Locally (0x5a) because max implem
ented version is 1
2021-04-15T22:41:56.741Z CNTRLR [Node 004] skipping query for Powerlevel (0x73) because max implemented vers
ion is 0
2021-04-15T22:41:56.743Z CNTRLR [Node 004] skipping query for Scene Actuator Configuration (0x2c) because ma
x implemented version is 1
2021-04-15T22:41:56.745Z CNTRLR [Node 004] skipping query for Scene Activation (0x2b) because max implemente
d version is 1
2021-04-15T22:41:56.748Z CNTRLR » [Node 004] querying the CC version for Firmware Update Meta Data...
2021-04-15T22:42:06.880Z CNTRLR [Node 004] Timed out while waiting for a response from the node
2021-04-15T22:42:06.887Z CNTRLR [Node 004] CC version query for Firmware Update Meta Data timed out - assuming
the node supports version 1...
2021-04-15T22:42:06.889Z CNTRLR [Node 004] skipping query for Hail (0x82) because max implemented version is
1
2021-04-15T22:42:06.906Z CNTRLR [Node 004] Interviewing Z-Wave Plus Info...
2021-04-15T22:42:06.908Z CNTRLR » [Node 004] querying Z-Wave+ information...
2021-04-15T22:42:17.038Z CNTRLR [Node 004] Timed out while waiting for a response from the node
2021-04-15T22:42:17.060Z CNTRLR [Node 004] Interviewing Binary Switch...
2021-04-15T22:42:17.064Z CNTRLR » [Node 004] querying Binary Switch state...
2021-04-15T22:42:27.267Z CNTRLR [Node 004] Timed out while waiting for a response from the node
2021-04-15T22:42:27.298Z CNTRLR [Node 004] Interviewing Configuration...
2021-04-15T22:42:27.300Z CNTRLR [Node 004] ConfigurationCC: skipping interview because CC version is < 3 and t
here is no config file
2021-04-15T22:42:27.306Z CNTRLR [Node 004] Interviewing Association...
2021-04-15T22:42:27.308Z CNTRLR » [Node 004] querying number of association groups...
2021-04-15T22:42:37.437Z CNTRLR [Node 004] Timed out while waiting for a response from the node
2021-04-15T22:42:37.444Z CNTRLR [Node 004] Querying association groups timed out, skipping interview...
2021-04-15T22:42:37.466Z CNTRLR [Node 004] Interviewing Association Group Information...
2021-04-15 18:42:37.470 INFO ZWAVE: Node 4: interview stage COMMANDCLASSES completed
2021-04-15T22:42:37.473Z CNTRLR [Node 004] Interview stage completed: CommandClasses
2021-04-15 18:42:37.475 INFO ZWAVE: Node 4: interview stage OVERWRITECONFIG completed
2021-04-15T22:42:37.477Z CNTRLR [Node 004] Interview stage completed: OverwriteConfig
2021-04-15T22:42:37.479Z CNTRLR » [Node 004] requesting node neighbors...
2021-04-15T22:42:37.521Z CNTRLR « [Node 004] node neighbors received: 1
2021-04-15 18:42:37.522 INFO ZWAVE: Node 4: interview stage NEIGHBORS completed
2021-04-15T22:42:37.524Z CNTRLR [Node 004] Interview stage completed: Neighbors
2021-04-15 18:42:37.526 INFO ZWAVE: Node 4: interview stage COMPLETE completed
2021-04-15T22:42:37.528Z CNTRLR [Node 004] Interview completed
2021-04-15 18:42:37.541 INFO ZWAVE: Node 4: value added 4-37-0-currentValue => undefined
2021-04-15 18:42:37.543 INFO ZWAVE: Node 4: value added 4-37-0-targetValue => undefined
2021-04-15 18:42:37.544 INFO ZWAVE: Node 4: value added 4-134-0-libraryType => undefined
2021-04-15 18:42:37.546 INFO ZWAVE: Node 4: value added 4-134-0-protocolVersion => undefined
2021-04-15 18:42:37.547 INFO ZWAVE: Node 4: value added 4-134-0-firmwareVersions => undefined
2021-04-15 18:42:37.549 INFO ZWAVE: Node 4: value added 4-114-0-manufacturerId => undefined
2021-04-15 18:42:37.551 INFO ZWAVE: Node 4: value added 4-114-0-productType => undefined
2021-04-15 18:42:37.556 INFO ZWAVE: Node 4: value added 4-114-0-productId => undefined
2021-04-15 18:42:37.557 INFO ZWAVE: Node 4: value added 4-43-0-sceneId => undefined
2021-04-15 18:42:37.559 INFO ZWAVE: Node 4: value added 4-43-0-dimmingDuration => undefined
2021-04-15 18:42:37.561 INFO ZWAVE: Node 4 ready: Unknown manufacturer 0xXXXX - Unknown product 0xXXXX (0xXXXX)
2021-04-15T22:42:37.562Z CNTRLR [Node 004] The node is ready to be used
2021-04-15 18:42:37.573 INFO ZWAVE: Node 4: interview COMPLETED, all values are updated

There are several mentions of timeouts, even when I had the raspberry within 5 feet of the switch and after doing a heal network.  There is only direct connections from the each device as I only have the switch, motion sensor and z-stick in the network right now.  You think this is still an integration issue?  They pushed me to open a ticket here as they thought the integration relied on info from the add-on.

**Comment by frogbite** [comment]
https://github.com/home-assistant/core/issues/49279 opened.
