### ISSUE TITLE
Exception during service call against Dead device

### ISSUE THREAD

**Issue by Masterz69** [hassio-addons/addon-zwavejs2mqtt#188]
# Problem/Motivation

Command / Service call to Dead device cause exception and automation fails to continue.

## Expected behavior

Command / Service call to Dead device must finish w/out exception with some return code.

## Actual behavior

![image](https://user-images.githubusercontent.com/15225823/119981038-d355a500-bfc5-11eb-9124-e60553a42cfc.png)

```txt
2021-05-28 14:41:12 ERROR (MainThread) [homeassistant.components.automation.shed_lights_on_no_motion] Shed Lights on No Motion: Repeat at step 1: Error executing script. Unexpected error for call_service at pos 1: Command failed: unknown_error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 366, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 566, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1481, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1516, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 726, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/zwave_js/switch.py", line 74, in async_turn_off
    await self.info.node.async_set_value(target_value, False)
  File "/usr/local/lib/python3.8/site-packages/zwave_js_server/model/node.py", line 375, in async_set_value
    result = await self.async_send_command(
  File "/usr/local/lib/python3.8/site-packages/zwave_js_server/model/node.py", line 354, in async_send_command
    result = await self.client.async_send_command(message, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/zwave_js_server/client.py", line 73, in async_send_command
    return await future
zwave_js_server.exceptions.FailedCommand: Command failed: unknown_error
2021-05-28 14:41:12 ERROR (MainThread) [homeassistant.components.automation.shed_lights_on_no_motion] Shed Lights on No Motion: Error executing script. Unexpected error for repeat at pos 1: Command failed: unknown_error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 366, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/trace.py", line 249, in async_wrapper
    await func(*args)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 719, in _async_repeat_step
    await async_run_sequence(iteration)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 674, in async_run_sequence
    await self._async_run_script(script)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 820, in _async_run_script
    await self._async_run_long_action(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 530, in _async_run_long_action
    long_task.result()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1212, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 348, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 366, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 566, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1481, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1516, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 726, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/zwave_js/switch.py", line 74, in async_turn_off
    await self.info.node.async_set_value(target_value, False)
  File "/usr/local/lib/python3.8/site-packages/zwave_js_server/model/node.py", line 375, in async_set_value
    result = await self.async_send_command(
  File "/usr/local/lib/python3.8/site-packages/zwave_js_server/model/node.py", line 354, in async_send_command
    result = await self.client.async_send_command(message, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/zwave_js_server/client.py", line 73, in async_send_command
    return await future
zwave_js_server.exceptions.FailedCommand: Command failed: unknown_error
2021-05-28 14:41:12 ERROR (MainThread) [homeassistant.components.automation.shed_lights_on_no_motion] While executing automation automation.shed_lights_on_no_motion
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 504, in async_trigger
    await self.action_script.async_run(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1212, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 348, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 366, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/trace.py", line 249, in async_wrapper
    await func(*args)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 719, in _async_repeat_step
    await async_run_sequence(iteration)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 674, in async_run_sequence
    await self._async_run_script(script)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 820, in _async_run_script
    await self._async_run_long_action(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 530, in _async_run_long_action
    long_task.result()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1212, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 348, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 366, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 566, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1481, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1516, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 726, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/zwave_js/switch.py", line 74, in async_turn_off
    await self.info.node.async_set_value(target_value, False)
  File "/usr/local/lib/python3.8/site-packages/zwave_js_server/model/node.py", line 375, in async_set_value
    result = await self.async_send_command(
  File "/usr/local/lib/python3.8/site-packages/zwave_js_server/model/node.py", line 354, in async_send_command
    result = await self.client.async_send_command(message, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/zwave_js_server/client.py", line 73, in async_send_command
    return await future
zwave_js_server.exceptions.FailedCommand: Command failed: unknown_error
2021-05-28 14:42:22 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'click' when rendering '{{ value_json.click }}'
2021-05-28 14:42:22 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'action' when rendering '{{ value_json.action }}'
2021-05-28 14:43:37 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'battery_low' when rendering '{{ value_json.battery_low }}'
2021-05-28 14:43:37 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'tamper' when rendering '{{ value_json.tamper }}'
2021-05-28 14:45:28 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Running websocket_api script
2021-05-28 14:45:28 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Executing step call service
2021-05-28 14:45:36 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: Command failed: unknown_error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 366, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 566, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1481, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1516, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 726, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/zwave_js/switch.py", line 74, in async_turn_off
    await self.info.node.async_set_value(target_value, False)
  File "/usr/local/lib/python3.8/site-packages/zwave_js_server/model/node.py", line 375, in async_set_value
    result = await self.async_send_command(
  File "/usr/local/lib/python3.8/site-packages/zwave_js_server/model/node.py", line 354, in async_send_command
    result = await self.client.async_send_command(message, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/zwave_js_server/client.py", line 73, in async_send_command
    return await future
zwave_js_server.exceptions.FailedCommand: Command failed: unknown_error
2021-05-28 14:45:36 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547260935040] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 21, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 482, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1212, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 348, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 366, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 566, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1481, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1516, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 726, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/zwave_js/switch.py", line 74, in async_turn_off
    await self.info.node.async_set_value(target_value, False)
  File "/usr/local/lib/python3.8/site-packages/zwave_js_server/model/node.py", line 375, in async_set_value
    result = await self.async_send_command(
  File "/usr/local/lib/python3.8/site-packages/zwave_js_server/model/node.py", line 354, in async_send_command
    result = await self.client.async_send_command(message, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/zwave_js_server/client.py", line 73, in async_send_command
    return await future
zwave_js_server.exceptions.FailedCommand: Command failed: unknown_error
```

[Related issue for HA Core.](https://github.com/home-assistant/core/issues/51201)

## Steps to reproduce

Call service turn_on/off against Dead ZWave device.

## Proposed changes
.

**Comment by frenck** [comment]
You are posing an integration with Home Assistant.. .this is not the Home Assistant repository.
