### ISSUE TITLE
Using zwave_js.set_config_parameter results in AttributeError

### ISSUE THREAD

**Issue by wigster** [hassio-addons/addon-zwavejs2mqtt#80]
# Problem/Motivation

I am trying to use an automation to control config parameters of my Thermostat Valves (Eurotronic Spirit Z-Wave). Config file here:

(https://github.com/zwave-js/node-zwave-js/blob/2a13c7de52b070a0ab0216293169b614d44adf2f/packages/config/config/devices/0x0148/spirit.json#L151-L167)

The appropriate values are integers between -50 and 50 as well as the special code -128.

## Expected behavior

The relevant part of my script "Heating: Correct TRV Salon Temp", reduced to the minimum, does the following:
```yaml
- service: zwave_js.set_config_parameter
      data:
        parameter: "8"
        value: 8
      target:
        device_id: 32ab6dc7b858f9a872df75b8d891bef7
```
I would then expect to see this value in the zwavejs2mqtt configuration view for the node. 

## Actual behavior

No parameter is set (nothing in the zwavejs2mqtt log) and an error is generated in the HASS log. I have attempted to wrap the value in quotes etc, but it did not help.

```
2021-03-08 19:22:14 ERROR (MainThread) [homeassistant.components.automation.correct_trv_salon_temp] Heating: Correct TRV Salon Temp: Error executing script. Unexpected error for call_service at pos 2: 'Value' object has no attribute 'configuration_value_type'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 262, in _async_step
    await getattr(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 463, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1488, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1523, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/zwave_js/services.py", line 107, in async_set_config_parameter
    zwave_value = await async_set_config_parameter(
  File "/usr/local/lib/python3.8/site-packages/zwave_js_server/util/node.py", line 59, in async_set_config_parameter
    zwave_value.configuration_value_type == ConfigurationValueType.ENUMERATED
AttributeError: 'Value' object has no attribute 'configuration_value_type'
2021-03-08 19:22:14 ERROR (MainThread) [homeassistant.components.automation.correct_trv_salon_temp] While executing automation automation.correct_trv_salon_temp
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 412, in async_trigger
    await self.action_script.async_run(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1041, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 254, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 262, in _async_step
    await getattr(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 463, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1488, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1523, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/zwave_js/services.py", line 107, in async_set_config_parameter
    zwave_value = await async_set_config_parameter(
  File "/usr/local/lib/python3.8/site-packages/zwave_js_server/util/node.py", line 59, in async_set_config_parameter
    zwave_value.configuration_value_type == ConfigurationValueType.ENUMERATED
AttributeError: 'Value' object has no attribute 'configuration_value_type'
```
I am running hass.io with core-2021.3.2 and upgraded the add-on to the new version today (0.6.1) with zwavejs2mqtt 2.1.2. There were some issues with v 2.1.0 but those got cleared up with today's version but the problem remains on the HASS side.

Here is a reference to my discussion on the Z2M github. As of today it is possible to set the value for this parameter through the Z2M Web GUI, but I need programmatic control.

https://github.com/zwave-js/zwavejs2mqtt/issues/806

**Comment by frenck** [comment]
You are reporting a Home Assistant integration issue with the add-on issue tracker, which is the wrong place. Please report issues with the Home Assistant integration, with Home Assistant.
